In [ ]:
#Import pandas for reading and analyzing CSV data:
#https://towardsdatascience.com/regular-expressions-regex-with-examples-in-python-and-pandas-461228335670

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

#read edit file
ufo = pd.read_csv('editufo.csv')
ufodur = ufo
nump = '\d?(-?)(\d?)'
pattern = '(!?(i?)(Sec.*|sec.*|Min.*|min.*|Ho.*|hour.*|hr.*))*'
ufodur['length'] = ufo['duration'].str.replace(pattern, '', regex=True)
ufodur['timeinterval'] = ufo['duration'].str.replace(nump, '', regex=True)
ufodur.head(15)

#rest is null
#cast as int

###time amount

def regexTime(length):
    time_duration = 1
    text = ""
    some = 'i?(Few|few|mere|Mere|some|Some|Couple|couple|Several|several)'
    #some takes lower end
    #if there are multiple numbers, split and average
    if (length is int or length is float): 
        time_duration = length
    else: text = str(length)
    if (len(text) == 0):
        time_duration = 1
        
    if (re.match(some, text)):
        time_duration = 5

    else:
    #findall (\d) and average
    #p = re.compiler(r'\d+') #findall int
        p = re.findall('\d+',text)
        sumP = 0
        for i in p:
            sumP += int(i)

        if (len(p) == 0):
            time_duration = 1
        else:
            average = sumP/len(p)
            time_duration = average
    return time_duration

###time interval
    
def regexInterval(interval):
    time_length = 0
    text = str(interval)
    #define a bunch of patterns for time
    minute = '(Min\w+)|(min\w+)'
    second = '(Sec\w+)|(sec\w+)'
    hour = '(Hour.*)|(hour.*)|(hr.*)|(hrs.*)'

    #case for each minute
    if (re.search(minute,text)):
        time_length = 60
    elif (re.search(second,text)):
        time_length = 1
    elif (re.search(hour,text)):
        time_length = 3600
        
    return time_length


ufodur['newlength']=ufodur['length'].apply(lambda a: regexTime(a))
ufodur['newtime']=ufodur['timeinterval'].apply(lambda a: regexInterval(a))
ufodur['duration_sec'] = (ufodur['newtime']*ufodur['newlength'])
ufodur['duration_sec'].replace(0, np.nan, inplace=True)
ufodur = ufodur.drop(columns=['newlength','newtime','length','timeinterval','duration'])
#print(regexInterval(ufodur['timeinterval'][0]))
ufodur.head(15)

,city,state,date_time,shape,text,city_latitude,city_longitude,duration_sec
0,Chester,VA,2019-12-12 18:43:00,light,My wife was driving southeast on a fairly popu...,37.343152,-77.408582,5.0
1,Rocky Hill,CT,2019-03-22 18:30:00,circle,I think that I may caught a UFO on the NBC Nig...,41.664800,-72.639300,4.0
2,Ottawa,ON,2019-04-17 02:00:00,teardrop,I was driving towards the intersection of fall...,45.381383,-75.708501,10.0
3,Peoria,NY,2009-03-15 18:00:00,cigar,"In Peoria, Arizona, I saw a cigar shaped craft...",NaN,NaN,120.0
4,Kirbyville,TX,2019-04-02 20:25:00,disk,"The object has flashing lights that are green,...",30.677200,-94.005200,900.0
5,Tucson,AZ,2019-05-01 11:00:00,unknown,"Description is the same as Washington, DC, eve...",32.259941,-110.927542,300.0
6,Gold Canyon,AZ,2019-04-10 17:00:00,circle,Apr. 10th we witnessed a very bright silvery r...,33.371500,-111.436900,600.0
7,Brookville,IN,2019-06-18 21:00:00,sphere,Metal orb of wires that was seen through a tel...,39.404700,-84.973600,3600.0
8,Melbourne Beach,FL,2019-06-12 22:00:00,unknown,We think 2 UFOs....2 tiny lights recorded for ...,27.966800,-80.509600,3600.0
9,Carrizozo,NM,2019-06-11 22:00:00,changing,I was driving and saw three glowing orbs is th...,33.784900,-105.833200,300.0
10,Waco,TX,2018-06-15 01:00:00,circle,I was in pool and my wife was sitting on the e...,31.573598,-97.135849,120.0
11,Yuba City,CA,2019-08-17 00:00:00,formation,There were 4 lights in diagonal formation that...,39.059811,-121.668256,1200.0
12,Abilene,TX,2019-08-14 01:00:00,light,star-like light that started bouncing in the a...,32.394351,-99.790044,30.0
13,Leyner,CO,2019-08-09 20:22:00,light,There where 4 bright lights in a shape of a di...,NaN,NaN,1200.0
14,Catalina,AZ,2019-08-09 20:30:00,cigar,My wife and I were taking our usual evening st...,NaN,NaN,40.0